export const organicFoods = [
  {
    id: 1,
    name: "Silk Almond Milk",
    image: "/Home/product-img20.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 2,
    name: "SunButter Sunflower",
    image: "/Home/product-img21.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 3,
    name: "Hemp Hearts",
    image: "/Home/product-img22.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 4,
    name: "Red Mill Granola",
    image: "/Home/product-img23.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 5,
    name: "Nutty Granola",
    image: "/Home/product-img24.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 6,
    name: "Organic Girl",
    image: "/Home/product-img25.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
];
export const NewArrival = [
  {
    id: 1,
    name: "Silk Almond Milk",
    image: "/Home/product-img20.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 2,
    name: "SunButter Sunflower",
    image: "/Home/product-img21.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 3,
    name: "Hemp Hearts",
    image: "/Home/product-img22.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 4,
    name: "Red Mill Granola",
    image: "/Home/product-img23.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 5,
    name: "Nutty Granola",
    image: "/Home/product-img24.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
  {
    id: 6,
    name: "Organic Girl",
    image: "/Home/product-img25.png",
    rating: 4.8,
    reviews: 17000,
    seller: "Lucky Supermarket",
    originalPrice: 28.99,
    discountedPrice: 14.99,
  },
];

export const weeklyTops = [
  {
    name: "Organic Market",
    color: "#f5f5e9",
    image: "/Home/vendor-logo1.png",
  },
  {
    name: "Safeway",
    color: "#e9f5f5",
    image: "/Home/vendor-logo2.png",
  },
  {
    name: "Food Max",
    color: "#f5e9f5",
    image: "/Home/vendor-logo3.png",
  },
  {
    name: "HRmart",
    color: "#f5ebe9",
    image: "/Home/vendor-logo4.png",
  },
  {
    name: "Organic Market",
    color: "#f5f5e9",
    image: "/Home/vendor-logo5.png",
  },
  {
    name: "Safeway",
    color: "#e9f5f5",
    image: "/Home/vendor-logo6.png",
  },
  {
    name: "Food Max",
    color: "#f5e9f5",
    image: "/Home/vendor-logo1.png",
  },
  {
    name: "HRmart",
    color: "#f5ebe9",
    image: "/Home/vendor-logo2.png",
  },
];

export const recommendeds = [
  {
    id: 1,
    name: "C-500 Antioxidant Protect Dietary...",
    brand: "By Lucky Supermarket",
    price: 14.99,
    originalPrice: 28.99,
    rating: 4.8,
    reviews: 17,
    image: "/Home/product-img1.png",
    saleTag: "Best Sale",
  },
  {
    id: 2,
    name: "Marcel's Modern Pantry Almond Unsweetened",
    brand: "By Lucky Supermarket",
    price: 14.99,
    originalPrice: 28.99,
    rating: 4.8,
    reviews: 17,
    image: "/Home/product-img2.png",
    saleTag: "Sale 50%",
  },
  {
    id: 3,
    name: "O Organics Milk, Whole, Vitamin D",
    brand: "By Lucky Supermarket",
    price: 14.99,
    originalPrice: 28.99,
    rating: 4.8,
    reviews: 17,
    image: "/Home/product-img3.png",
  },
  {
    id: 4,
    name: "Whole Grains and Seeds Organic Bread",
    brand: "By Lucky Supermarket",
    price: 14.99,
    originalPrice: 28.99,
    rating: 4.8,
    reviews: 17,
    image: "/Home/product-img1.png",
    saleTag: "Best Sale",
  },
  {
    id: 5,
    name: "Lucerne Yogurt, Lowfat, Strawberry",
    brand: "By Lucky Supermarket",
    price: 14.99,
    originalPrice: 28.99,
    rating: 4.8,
    reviews: 17,
    image: "/Home/product-img5.png",
    saleTag: "Sale 50%",
  },
  {
    id: 6,
    name: "Nature Valley Whole Grain Oats and Honey...",
    brand: "By Lucky Supermarket",
    price: 14.99,
    originalPrice: 28.99,
    rating: 4.8,
    reviews: 17,
    image: "/Home/product-img6.png",
  },
];

export const freshProducts = [
  {
    name: "Vegetables",
    image: "/Home/feature-img7.png",
    products: "125+ Products",
  },
  {
    name: "Fish & Meats",
    image: "/Home/feature-img2.png",
    products: "125+ Products",
  },
  {
    name: "Desserts",
    image: "/Home/feature-img4.png",
    products: "125+ Products",
  },
  {
    name: "Drinks & Juice",
    image: "/Home/feature-img3.png",
    products: "125+ Products",
  },
  {
    name: "Animals Food",
    image: "/Home/feature-img5.png",
    products: "125+ Products",
  },
  {
    name: "Fresh Fruits",
    image: "/Home/feature-img6.png",
    products: "125+ Products",
  },
];

export const flashSalesBottom = [
  {
    id: 1,
    image: "/Home/offer-img1.png",
    alt: "Basket of fresh produce and groceries",
    title: "$5 off your first order",
    description: "Delivery by 6:15am expired Aug 5",
  },
  {
    id: 2,
    image: "/Home/offer-img2.png",
    alt: "Fresh fish with lemon slices and herbs",
    title: "$5 off your first order",
    description: "Delivery by 6:15am expired Aug 5",
  },
];

export const flashSales = [
  {
    id: 1,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Home/product-img1.png",
    originalPrice: 28.99,
    discountedPrice: 14.99,
    rating: 4.8,
    reviews: "17k",
    seller: "Lucky Supermarket",
    sold: 18,
    total: 35,
  },
  {
    id: 2,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Home/product-img2.png",
    originalPrice: 28.99,
    discountedPrice: 14.99,
    rating: 4.8,
    reviews: "17k",
    seller: "Lucky Supermarket",
    sold: 18,
    total: 35,
  },
  {
    id: 3,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Home/product-img3.png",
    originalPrice: 28.99,
    discountedPrice: 14.99,
    rating: 4.8,
    reviews: "17k",
    seller: "Lucky Supermarket",
    sold: 18,
    total: 35,
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Home/product-img1.png",
    originalPrice: 28.99,
    discountedPrice: 14.99,
    rating: 4.8,
    reviews: "17k",
    seller: "Lucky Supermarket",
    sold: 18,
    total: 35,
  },
  {
    id: 5,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Home/product-img5.png",
    originalPrice: 28.99,
    discountedPrice: 14.99,
    rating: 4.8,
    reviews: "17k",
    seller: "Lucky Supermarket",
    sold: 18,
    total: 35,
  },
  {
    id: 6,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Home/product-img6.png",
    originalPrice: 28.99,
    discountedPrice: 14.99,
    rating: 4.8,
    reviews: "17k",
    seller: "Lucky Supermarket",
    sold: 18,
    total: 35,
  },
];

export const productItems = [
  {
    name: "Taylor Farms Broccoli...",
    price: 1500.0,
    image: "/Home/short-product-img5.png",
  },
  {
    name: "Taylor Farms Broccoli...",
    price: 1500.0,
    image: "/Home/short-product-img6.png",
  },
  {
    name: "Taylor Farms Broccoli...",
    price: 1500.0,
    image: "/Home/short-product-img7.png",
  },
  {
    name: "Taylor Farms Broccoli...",
    price: 1500.0,
    image: "/Home/short-product-img8.png",
  },
];

export const productSections = [
  { title: "Featured Products" },
  { title: "Top Selling Products" },
  { title: "On-sale Products" },
  { title: "Top Rated Products" },
];

export const brands = [
  { name: "Organic Healthy Food", image: "/Home/brand-img1.png" },
  { name: "Passion For Organic Quality", image: "/Home/brand-img2.png" },
  { name: "The Organic Shop", image: "/Home/brand-img3.png" },
  { name: "The Best Organic Food", image: "/Home/brand-img4.png" },
  { name: "Passion For Organic Quality", image: "/Home/brand-img6.png" },
  { name: "The Organic Shop", image: "/Home/brand-img1.png" },
];

export const FreshProductsCards = [
  {
    title: "Everyday Fresh Meat",
    image: "/Home/featureBanner-img1.png",
    color: "bg-yellow-50",
  },
  {
    title: "Daily Fresh Vegetables",
    image: "/Home/featureBanner-img2.png",
    color: "bg-green-50",
  },
  {
    title: "Everyday Fresh Milk",
    image: "/Home/featureBanner-img3.png",
    color: "bg-pink-50",
  },
  {
    title: "Everyday Fresh Fruits",
    image: "/Home/featureBanner-img4.png",
    color: "bg-yellow-50",
  },
];

export const ShopMainProducts = [
  {
    id: 1,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img1.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Best Sale",
  },
  {
    id: 2,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img2.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
  },
  {
    id: 3,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img3.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img4.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img5.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img6.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img7.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img8.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img9.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img10.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
  {
    id: 4,
    name: "Taylor Farms Broccoli Florets Vegetables",
    image: "/Shop/product-two-img4.png",
    rating: 4.8,
    reviews: "17k",
    originalPrice: 28.99,
    salePrice: 14.99,
    sold: 18,
    total: 35,
    label: "Sale 50%",
  },
];
